### ISSUE TITLE
Проблема с аббревиатурами (РФ и т.п.)

### ISSUE THREAD

**Issue by pandanapande** [mrauhu/web-typography-standards#6]
Исходное предложение: 

Недавно мы получили ответ из Министерства здравоохранения и социального развития РФ.

Результат типографа:

Недавно мы получили ответ из Министерства здравоохранения и социального развития Р. Ф.

(Лишняя точка и пробел между Р и Ф)

Можно ли что-нибудь сделать?

Привет!

**Comment by ram108** [comment]
Отправил отчет о баге автору типографа Евгению Мураьеву (emuravjev@gmail.com). Обещал посмотреть.
